//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSoft.FMPCloud {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StaticResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBSoft.FMPCloud.StaticResources", typeof(StaticResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fmpcloud.io/api/.
        /// </summary>
        internal static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/profile/.
        /// </summary>
        internal static string CompanyProfilePath {
            get {
                return ResourceManager.GetString("CompanyProfilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/dowjones_constituent.
        /// </summary>
        internal static string DowJonesPath {
            get {
                return ResourceManager.GetString("DowJonesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/historical/dowjones_constituent.
        /// </summary>
        internal static string DownJonesHistoricalPath {
            get {
                return ResourceManager.GetString("DownJonesHistoricalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/etf/list.
        /// </summary>
        internal static string EtfListPath {
            get {
                return ResourceManager.GetString("EtfListPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/historical-chart/.
        /// </summary>
        internal static string HistoricalChartPath {
            get {
                return ResourceManager.GetString("HistoricalChartPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/historical-price-full/.
        /// </summary>
        internal static string HistoricalPricePath {
            get {
                return ResourceManager.GetString("HistoricalPricePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/historical-sectors-performance.
        /// </summary>
        internal static string HistoricalSectorPerformancePath {
            get {
                return ResourceManager.GetString("HistoricalSectorPerformancePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/key-executives/.
        /// </summary>
        internal static string KeyExecutivesPath {
            get {
                return ResourceManager.GetString("KeyExecutivesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/symbol/.
        /// </summary>
        internal static string MarketAvailablePath {
            get {
                return ResourceManager.GetString("MarketAvailablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/quotes/.
        /// </summary>
        internal static string MarketQuotesPath {
            get {
                return ResourceManager.GetString("MarketQuotesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/historical/nasdaq_constituent.
        /// </summary>
        internal static string Nasdaq100HistoricalPath {
            get {
                return ResourceManager.GetString("Nasdaq100HistoricalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/nasdaq_constituent.
        /// </summary>
        internal static string Nasdaq100Path {
            get {
                return ResourceManager.GetString("Nasdaq100Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/quote/.
        /// </summary>
        internal static string RealTimeQuotePath {
            get {
                return ResourceManager.GetString("RealTimeQuotePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/sectors-performance.
        /// </summary>
        internal static string SectorPerformancePath {
            get {
                return ResourceManager.GetString("SectorPerformancePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/historical/sp500_constituent.
        /// </summary>
        internal static string SP500HistoricalPath {
            get {
                return ResourceManager.GetString("SP500HistoricalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/sp500_constituent.
        /// </summary>
        internal static string SP500Path {
            get {
                return ResourceManager.GetString("SP500Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/historical-price-full/stock_dividend/.
        /// </summary>
        internal static string StockDividendPath {
            get {
                return ResourceManager.GetString("StockDividendPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/stock/list.
        /// </summary>
        internal static string StockListPath {
            get {
                return ResourceManager.GetString("StockListPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/historical-price-full/stock_split/.
        /// </summary>
        internal static string StockSplitPath {
            get {
                return ResourceManager.GetString("StockSplitPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/search.
        /// </summary>
        internal static string TickerSearchPath {
            get {
                return ResourceManager.GetString("TickerSearchPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/actives.
        /// </summary>
        internal static string TopActivesPath {
            get {
                return ResourceManager.GetString("TopActivesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/gainers.
        /// </summary>
        internal static string TopGainersPath {
            get {
                return ResourceManager.GetString("TopGainersPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/losers.
        /// </summary>
        internal static string TopLosersPath {
            get {
                return ResourceManager.GetString("TopLosersPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/available-traded/list.
        /// </summary>
        internal static string TradableListPath {
            get {
                return ResourceManager.GetString("TradableListPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v3/market-hours.
        /// </summary>
        internal static string TradingHoursPath {
            get {
                return ResourceManager.GetString("TradingHoursPath", resourceCulture);
            }
        }
    }
}
